#!/usr/bin/env bash
MessageFile=$1
Ticket=$(git branch --show-current | grep -oe '[A-Z]\+-[0-9]\+')

if [[ ! $Ticket ]]; then
    exit
fi

messageContents=$(<$MessageFile)
echo -n "$Ticket " > $MessageFile
echo -n "$messageContents" >> $MessageFile